/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const GameId = IDL.Text;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const GameMetadata = IDL.Record({
  'id' : GameId,
  'title' : IDL.Text,
  'thumbnail' : ExternalBlob,
  'playable' : IDL.Bool,
  'description' : IDL.Text,
  'category' : IDL.Text,
});
export const SessionId = IDL.Text;
export const MessageId = IDL.Text;
export const Message = IDL.Record({
  'id' : MessageId,
  'content' : IDL.Text,
  'timestamp' : IDL.Nat64,
});
export const ArtworkId = IDL.Text;
export const MusicId = IDL.Text;
export const GameCatalogueView = IDL.Record({
  'id' : GameId,
  'title' : IDL.Text,
  'playable' : IDL.Bool,
  'description' : IDL.Text,
  'hasThumbnail' : IDL.Bool,
  'category' : IDL.Text,
});
export const SessionView = IDL.Record({
  'id' : SessionId,
  'messages' : IDL.Vec(Message),
  'lastActive' : IDL.Nat64,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addGameMetadata' : IDL.Func([GameMetadata], [], []),
  'addMessageToSession' : IDL.Func([SessionId, Message], [], []),
  'getAllArtworks' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(ArtworkId, ExternalBlob))],
      ['query'],
    ),
  'getAllMusic' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(MusicId, ExternalBlob))],
      ['query'],
    ),
  'getGameCatalogue' : IDL.Func([], [IDL.Vec(GameCatalogueView)], ['query']),
  'getGameMetadata' : IDL.Func([GameId], [GameMetadata], ['query']),
  'getSession' : IDL.Func([SessionId], [SessionView], ['query']),
  'getUserSessions' : IDL.Func([], [IDL.Vec(SessionView)], ['query']),
  'registerUser' : IDL.Func([], [], []),
  'retrieveArtwork' : IDL.Func([ArtworkId], [ExternalBlob], ['query']),
  'retrieveMusic' : IDL.Func([MusicId], [ExternalBlob], ['query']),
  'shareArtwork' : IDL.Func([ArtworkId, ExternalBlob], [], []),
  'shareMusic' : IDL.Func([MusicId, ExternalBlob], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const GameId = IDL.Text;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const GameMetadata = IDL.Record({
    'id' : GameId,
    'title' : IDL.Text,
    'thumbnail' : ExternalBlob,
    'playable' : IDL.Bool,
    'description' : IDL.Text,
    'category' : IDL.Text,
  });
  const SessionId = IDL.Text;
  const MessageId = IDL.Text;
  const Message = IDL.Record({
    'id' : MessageId,
    'content' : IDL.Text,
    'timestamp' : IDL.Nat64,
  });
  const ArtworkId = IDL.Text;
  const MusicId = IDL.Text;
  const GameCatalogueView = IDL.Record({
    'id' : GameId,
    'title' : IDL.Text,
    'playable' : IDL.Bool,
    'description' : IDL.Text,
    'hasThumbnail' : IDL.Bool,
    'category' : IDL.Text,
  });
  const SessionView = IDL.Record({
    'id' : SessionId,
    'messages' : IDL.Vec(Message),
    'lastActive' : IDL.Nat64,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addGameMetadata' : IDL.Func([GameMetadata], [], []),
    'addMessageToSession' : IDL.Func([SessionId, Message], [], []),
    'getAllArtworks' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(ArtworkId, ExternalBlob))],
        ['query'],
      ),
    'getAllMusic' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(MusicId, ExternalBlob))],
        ['query'],
      ),
    'getGameCatalogue' : IDL.Func([], [IDL.Vec(GameCatalogueView)], ['query']),
    'getGameMetadata' : IDL.Func([GameId], [GameMetadata], ['query']),
    'getSession' : IDL.Func([SessionId], [SessionView], ['query']),
    'getUserSessions' : IDL.Func([], [IDL.Vec(SessionView)], ['query']),
    'registerUser' : IDL.Func([], [], []),
    'retrieveArtwork' : IDL.Func([ArtworkId], [ExternalBlob], ['query']),
    'retrieveMusic' : IDL.Func([MusicId], [ExternalBlob], ['query']),
    'shareArtwork' : IDL.Func([ArtworkId, ExternalBlob], [], []),
    'shareMusic' : IDL.Func([MusicId, ExternalBlob], [], []),
  });
};

export const init = ({ IDL }) => { return []; };