/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ArtworkId = string;
export type ExternalBlob = Uint8Array;
export interface Message {
  'id' : MessageId,
  'content' : string,
  'timestamp' : bigint,
}
export type MessageId = string;
export type MusicId = string;
export type SessionId = string;
export interface SessionView {
  'id' : SessionId,
  'messages' : Array<Message>,
  'lastActive' : bigint,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addMessageToSession' : ActorMethod<[SessionId, Message], undefined>,
  'getAllArtworks' : ActorMethod<[], Array<[ArtworkId, ExternalBlob]>>,
  'getAllMusic' : ActorMethod<[], Array<[MusicId, ExternalBlob]>>,
  'getSession' : ActorMethod<[SessionId], SessionView>,
  'getUserSessions' : ActorMethod<[], Array<SessionView>>,
  'registerUser' : ActorMethod<[], undefined>,
  'retrieveArtwork' : ActorMethod<[ArtworkId], ExternalBlob>,
  'retrieveMusic' : ActorMethod<[MusicId], ExternalBlob>,
  'shareArtwork' : ActorMethod<[ArtworkId, ExternalBlob], undefined>,
  'shareMusic' : ActorMethod<[MusicId, ExternalBlob], undefined>,
  'solveMathProblem' : ActorMethod<[string], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];